### ISSUE TITLE
Typo on your Medium article (Epidemic Modeling 101: Or why your CoVID19 exponential fits are wrong)

### ISSUE THREAD

**Issue by p16i** [DataForScience/Epidemiology101#1]
Hi,

Thank you very much for your Epidemic Modeling 101 article.

There seems to have a small typo. Because I can't access the article due to membership restriction, I hope you don't mind if I report it here. Please see the attached image:
<img width="772" alt="image" src="https://user-images.githubusercontent.com/1214890/77897919-9d5e4900-727a-11ea-8961-8f56e7497940.png">

Reference:
https://medium.com/data-for-science/epidemic-modeling-101-or-why-your-covid19-exponential-fits-are-wrong-97aa50c55f8

**Comment by VladCarare** [comment]
Hi, 

Also, it seems to me that the left hand side of 
![image](https://user-images.githubusercontent.com/50262527/77908028-a3582800-7282-11ea-881c-5f240452fc3e.png)
should read I(t), with no derivative. 

Warm regards,
Vlad

**Comment by bmtgoncalves** [comment]
Fixed. Thank you.
*******************************************
Bruno Miguel Tavares Gonçalves, PhD
Homepage: www.bgoncalves.com
Email: bgoncalves@gmail.com
Twitter: @bgoncalves
*******************************************

**Comment by bmtgoncalves** [comment]
Fixed. Thank you.
*******************************************
Bruno Miguel Tavares Gonçalves, PhD
Homepage: www.bgoncalves.com
Email: bgoncalves@gmail.com
Twitter: @bgoncalves
*******************************************

**Comment by alessandro-gentilini** [comment]
@bmtgoncalves I see a "faction", maybe it should be "fraction", shouldn't it?
![image](https://user-images.githubusercontent.com/2438459/77935654-044b2480-72b2-11ea-8154-f8c9a4a89612.png)
Thank you!

**Comment by bmtgoncalves** [comment]
Fixed. Thank you.

**Comment by p16i** [comment]
I close the issue now. Thanks again for the article!
