### ISSUE TITLE
Perhaps publish your post's contents on GitHub in addition / instead of Medium?

### ISSUE THREAD

**Issue by ryan-p-randall** [DataForScience/Epidemiology101#3]
I profoundly appreciate your posts and that you've made your notebooks available here. Having read a few posts, I'm now being asked to pay for a Medium account in order to finish the series. I assume that you've chosen Medium for discoverability, which is completely understandable. It's unfortunately also a barrier.  

Would you consider publishing the content of your Medium posts here on GitHub, either through GitHub Pages or in simpler .md files?  

Thank you for considering this!

**Comment by bmtgoncalves** [comment]
Hi,

Thank you for reaching out. I've updated the links to Friend links. You should be able to read them now.
B
